name: CI Suma Python

on:
  push:
    branches: [ "main", "feature/leidy" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sumar-en-python:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout repositorio
      uses: actions/checkout@v4

    # 2. Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Ejecutar el script apuntando a la carpeta src/
    - name: Ejecutar suma.py
      run: python src/suma.py