name: Desplegar Calculadora Web

on:
  push:
    branches:
      - feature/leidy

# Permisos requeridos para poder publicar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Entorno necesario para el despliegue
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generar Calculadora con Python
        run: |
          mkdir public
          cd public
          python ../src/suma.py

      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Generar link directo en el Summary
        run: |
          echo "🎉 **¡Despliegue Exitoso!**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Haz clic en el enlace de abajo para abrir tu calculadora en una pestaña nueva:" >> $GITHUB_STEP_SUMMARY
          echo "👉 [**ABRIR CALCULADORA WEB**](${{ steps.deployment.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY