name: Desplegar Calculadora Web

on:
  push:
    branches: [ "main", "feature/leidy" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ejecutar script de Python para crear la web
        run: python src/suma.py

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4